# pytorch basics


In [114]:
import torch
from torch import nn

# tensor basics

In [115]:
# generall 3 is mostly used and then 2 d
# 4d tensor is just 3d tensor with last dimension just as array 
t = torch.rand(size=(2,3,4,5))
# t = torch.rand(size=(2,3,4))

print(f'tensor: {t}')

tensor: tensor([[[[0.9959, 0.6233, 0.7952, 0.8876, 0.4791],
          [0.4771, 0.6017, 0.6354, 0.5171, 0.7281],
          [0.6736, 0.3320, 0.5155, 0.3586, 0.1952],
          [0.2467, 0.1193, 0.4496, 0.2860, 0.0805]],

         [[0.9386, 0.1170, 0.3307, 0.3348, 0.4056],
          [0.2674, 0.9489, 0.6987, 0.2693, 0.0271],
          [0.9754, 0.6091, 0.0607, 0.4860, 0.3923],
          [0.1292, 0.0024, 0.7684, 0.3059, 0.4738]],

         [[0.4505, 0.4323, 0.6591, 0.3437, 0.7971],
          [0.2032, 0.6988, 0.1278, 0.0558, 0.7195],
          [0.5669, 0.0681, 0.9151, 0.8431, 0.7289],
          [0.7627, 0.3015, 0.2426, 0.8423, 0.6755]]],


        [[[0.5554, 0.1653, 0.6469, 0.4798, 0.7879],
          [0.6348, 0.9374, 0.4714, 0.8439, 0.2925],
          [0.8287, 0.7789, 0.7256, 0.4816, 0.5100],
          [0.2414, 0.9486, 0.2341, 0.2894, 0.4122]],

         [[0.6146, 0.4726, 0.7810, 0.9279, 0.1455],
          [0.1664, 0.0396, 0.9354, 0.0778, 0.9027],
          [0.0020, 0.6663, 0.8229, 0.1453, 0.7

# giving data type to the tensors

In [116]:
t = torch.rand(size=(2,2),dtype=torch.float32)
print(f"tensor:{t}")

tensor:tensor([[0.0581, 0.4171],
        [0.0068, 0.1852]])


# creating zeros and ones tensor

In [117]:
t = torch.zeros(size=(2,3,4),dtype=torch.float16)
print(f"tensors: {t}")

tensors: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=torch.float16)


In [118]:
t = torch.ones(size=(2,3,4),dtype=torch.float64)
print(f"tensor: {t}")

tensor: tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float64)


# getting tensor basic properties

In [119]:
# python list 
a= [
    [[1,2,3],[2,3,4],[3,4,5],[12,24,53]],
    [[1,3,2],[10,3,5],[10,13,13],[32,53,45]],
    [[1,3,4],[11,5,10],[16,33,53],[34,53,34]],
    [[2,6,6],[69,94,1],[16,78,43],[34,56,89]],
    [[0,34,4],[48,9,14],[16,34,54],[3,32,32]],
    ]
# t = torch.tensor(data=t,dtype=torch.float,device="cuda")
t = torch.tensor(data=a,dtype=torch.float,device="cpu")

print(f"tensor: {t}")
print(f"shape: {t.shape}")
print(f"rank: {torch.linalg.matrix_rank(t)}")
print(f"device:{t.device}")
print(f"Datatype of tensor: {t.dtype}")
print(f"size:{t.size()}")

tensor: tensor([[[ 1.,  2.,  3.],
         [ 2.,  3.,  4.],
         [ 3.,  4.,  5.],
         [12., 24., 53.]],

        [[ 1.,  3.,  2.],
         [10.,  3.,  5.],
         [10., 13., 13.],
         [32., 53., 45.]],

        [[ 1.,  3.,  4.],
         [11.,  5., 10.],
         [16., 33., 53.],
         [34., 53., 34.]],

        [[ 2.,  6.,  6.],
         [69., 94.,  1.],
         [16., 78., 43.],
         [34., 56., 89.]],

        [[ 0., 34.,  4.],
         [48.,  9., 14.],
         [16., 34., 54.],
         [ 3., 32., 32.]]])
shape: torch.Size([5, 4, 3])
rank: tensor([3, 3, 3, 3, 3])
device:cpu
Datatype of tensor: torch.float32
size:torch.Size([5, 4, 3])


# operation vs in tensor operation
 these all perform element wise division
```
+ or add
- or sub
* or mul 
/ or div 

```


In [120]:
a = torch.rand((2,2),dtype=torch.float32)
b = torch.rand((2,2),dtype=torch.float32)

# operation
c = torch.add(a,b)

print(f"c after add operation :{c} ")
c = a + b 
print(f"c after + operation :{c}")


# in value operation
# every underscore(_) is in value operation
print(f"c before addition : {c}")

c.add_(b)
print(f"c after addition:{c}")


c after add operation :tensor([[0.5824, 1.1766],
        [0.4174, 0.8452]]) 
c after + operation :tensor([[0.5824, 1.1766],
        [0.4174, 0.8452]])
c before addition : tensor([[0.5824, 1.1766],
        [0.4174, 0.8452]])
c after addition:tensor([[0.8847, 2.0642],
        [0.4756, 1.3271]])


In [121]:
a = [[5,10,15],[20,25,30]]

a = torch.tensor(data=a,dtype=torch.float32)
print(f"a:{a}")
b = torch.ones(2,3,dtype=torch.float32)
b = b * 5
print(f"b : {b}")
c = a / b
# c = torch.div(a,b)
print(f"c:{c}")

a:tensor([[ 5., 10., 15.],
        [20., 25., 30.]])
b : tensor([[5., 5., 5.],
        [5., 5., 5.]])
c:tensor([[1., 2., 3.],
        [4., 5., 6.]])


# Accessing the tensor values

In [122]:
a = [[1,3],[3],[[4,5]]]
# you cannot have different lengths of x,y,z on tensors
# ERROR: expected sequence of length 2 at dim 1 (got 1)
# a = torch.tensor(a)


In [123]:
a = torch.rand(size=(4,3,3),dtype=torch.float32)
print(a)
# give index to access starting from zero
#NOTE: for better understanding 
# view as higher dimension tensor as the element of the 3d tensor 
print(f"a[0] is starting surface:\n {a[0]}")

print(f"a[0,0] is the first row of a[0] surface:\n {a[0,0]}")

print(f"a[0,0,0] is the first element of a[0,0] row:\n {a[0,0,0]}")

tensor([[[0.3227, 0.6328, 0.1937],
         [0.4060, 0.1921, 0.7416],
         [0.4749, 0.6522, 0.9879]],

        [[0.6943, 0.6406, 0.7844],
         [0.3685, 0.0216, 0.8882],
         [0.7567, 0.8127, 0.4155]],

        [[0.5506, 0.2698, 0.7548],
         [0.2157, 0.2743, 0.8858],
         [0.5782, 0.7146, 0.1247]],

        [[0.7935, 0.5813, 0.6807],
         [0.1123, 0.5562, 0.9028],
         [0.7809, 0.1615, 0.3804]]])
a[0] is starting surface:
 tensor([[0.3227, 0.6328, 0.1937],
        [0.4060, 0.1921, 0.7416],
        [0.4749, 0.6522, 0.9879]])
a[0,0] is the first row of a[0] surface:
 tensor([0.3227, 0.6328, 0.1937])
a[0,0,0] is the first element of a[0,0] row:
 0.3226662278175354


# reshaping in pytorch

In [124]:
x = torch.rand(size=(2,3,4))
num = torch.numel(x)
print(f"number of total element in tensor : {num}")

# -1 means auto find the number of surface
a = x.view(-1,int(num/8))
# b = x.view(-1,-1,2) # RuntimeError: only one dimension can be inferred
b = x.view(-1,2,6)
print(f"x:\n {x}")
print(f"y:\n {a}")
print(f"b:\n {b}")
print(f"size or shapeof b:{b.shape} or {b.size()}")

number of total element in tensor : 24
x:
 tensor([[[0.0864, 0.4451, 0.7590, 0.2011],
         [0.4279, 0.4783, 0.3981, 0.1847],
         [0.7718, 0.0858, 0.7004, 0.9996]],

        [[0.8075, 0.3373, 0.2590, 0.7142],
         [0.9869, 0.2954, 0.0187, 0.8719],
         [0.7840, 0.0431, 0.1601, 0.2844]]])
y:
 tensor([[0.0864, 0.4451, 0.7590],
        [0.2011, 0.4279, 0.4783],
        [0.3981, 0.1847, 0.7718],
        [0.0858, 0.7004, 0.9996],
        [0.8075, 0.3373, 0.2590],
        [0.7142, 0.9869, 0.2954],
        [0.0187, 0.8719, 0.7840],
        [0.0431, 0.1601, 0.2844]])
b:
 tensor([[[0.0864, 0.4451, 0.7590, 0.2011, 0.4279, 0.4783],
         [0.3981, 0.1847, 0.7718, 0.0858, 0.7004, 0.9996]],

        [[0.8075, 0.3373, 0.2590, 0.7142, 0.9869, 0.2954],
         [0.0187, 0.8719, 0.7840, 0.0431, 0.1601, 0.2844]]])
size or shapeof b:torch.Size([2, 2, 6]) or torch.Size([2, 2, 6])


# numpy into  tensor and vice verso

In [125]:
import numpy as np

In [126]:
a = torch.ones(size=(2,3,5))

# coverting tensor to numpy
b = a.numpy()

# now you can do all attributes of numpy and call any method supported by numpy
print(f"a is tensor:\n {a}")
print(f"b is numpy:\n {b}")
print(f"type of a: {type(a)} and type of b: {type(b)}")

a is tensor:
 tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
b is numpy:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
type of a: <class 'torch.Tensor'> and type of b: <class 'numpy.ndarray'>


## both the numpy array and the tensor share the same memory location


In [127]:
a = torch.ones(size=(2,3,5))

# coverting tensor to numpy
b = a.numpy()
print("_______________________before________________________")
print(f"a: {a}")
print(f"b: {b}")

# after torch operation
a.add_(1)
print("________________________after torch operation _____________")
print(f"a:{a}")
print(f"b:{b}")

# after numpy operation
# NOTE: after numpy operation the memory is not shared
b = b + 1
print("________________________after numpy operation memory is not _____________")
print(f"a:{a}")
print(f"b:{b}")


# after torch operation
a.add_(23)
print("________________________after torch operation _____________")
print(f"a:{a}")
print(f"b:{b}")





_______________________before________________________
a: tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
b: [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
________________________after torch operation _____________
a:tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])
b:[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]
________________________after numpy operation memory is not _____________
a:tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2

## converting the numpy to tensor 


and don't share same memory location too if they uses cpu

In [128]:
a = np.ones((2,5))

b = torch.from_numpy(a)

print("---------------------------before----------------------")
print(f"a: {a}")
print(f"b: {b}")

# operation on torch
b.add_(23)


print("---------------------------after torch operation----------------------")
print(f"a: {a}")
print(f"b: {b}")

# operation on numpy
a = a + 1

print("---------------------------after numpy operation memory is not shared----------------------")
print(f"a: {a}")
print(f"b: {b}")

# operation on torch
b.add_(20)


print("---------------------------after torch operation----------------------")
print(f"a: {a}")
print(f"b: {b}")

---------------------------before----------------------
a: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
b: tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
---------------------------after torch operation----------------------
a: [[24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24.]]
b: tensor([[24., 24., 24., 24., 24.],
        [24., 24., 24., 24., 24.]], dtype=torch.float64)
---------------------------after numpy operation memory is not shared----------------------
a: [[25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]]
b: tensor([[24., 24., 24., 24., 24.],
        [24., 24., 24., 24., 24.]], dtype=torch.float64)
---------------------------after torch operation----------------------
a: [[25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]]
b: tensor([[44., 44., 44., 44., 44.],
        [44., 44., 44., 44., 44.]], dtype=torch.float64)


# using the cuda device for training

In [129]:
torch.cuda.is_available()

False

In [130]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    a = torch.rand((2,3),device=device)
    # b is iniatially used in the cpu
    b = torch.rand((2,3))
    # b is now moved to gpu(cuda)
    b = b.to(device)
    
    c = a + b

    # a,b,c cannot be converted to numpy
    # a,b,c is used loaded in cuda
    # c = c.numpy() # error

    # to  convert to numpy array you need to use cpu

    c = c.to("cpu")
    c = c.numpy()


# requires_grads = True
for those which needs to be optimized and need to calculate gradient for those variable

In [131]:
x = torch.ones((2,3),requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
