# cross Entropy loss function

used with softmax and cross entropy loss function

![cross entropy loss function](assets\softmax.png)
![cross entropy loss function](assets\softmax_layer.png)


![cross entropy loss function](assets\cross_entropy_loss_function.png)

## in pytorch be careful

![cross entropy loss function](assets\cross_entropy_loss_function_care_ful_in_pytorch.png)


In [1]:
import numpy as np
import torch
import torch.nn as nn

## numpy implementation

In [65]:


# y_predict 
# y = np.array([2,.1,.5],dtype = np.float32)
def soft_max(x):
    '''
    params:
        x (2d-array) : input with shape (n_sample,features)
    '''
    sum = np.sum(np.exp(x),axis=1) # (n_sample)
    sum = np.reshape(sum,(sum.shape[0],1))
    result = np.divide(np.exp(x) , sum)

    return result

def cross_entropy_loss(y,y_predict):

    '''
    params:
        y (2d-array) : tesor with shape of (n_sample,)
        y_predict (2d-array) : tensor with shape of (n_sample,features)
    
    returns:
        loss (2d-array) : tensor with shape of (n_sample,1) 
        
    '''
    element_wise_multiply  = np.multiply(y,np.log(y_predict))
    loss = -1/y.shape[0] * np.sum(element_wise_multiply,axis=1)
    loss = loss.reshape(loss.shape[0],1)
    return loss




In [68]:
multiple_sample = [
    [2,1,3],
    [3,14,5],
    [10,3,1],
]
y_actual = [
    [0,0,1],
    [0,1,0],
    [0,0,1],
]

multiple_sample = np.array(multiple_sample)
y_actual = np.array(y_actual)

y_predict = soft_max(multiple_sample)

loss = cross_entropy_loss(y=y_actual,y_predict=y_predict)

print(f" y_predicted:{y_predict}")
print(f" loss :{loss}")


 y_predicted:[[2.44728471e-01 9.00305732e-02 6.65240956e-01]
 [1.66993610e-05 9.99859908e-01 1.23392515e-04]
 [9.98965779e-01 9.10938878e-04 1.23282171e-04]]
 loss :[[1.35868655e-01]
 [4.67005634e-05]
 [3.00034492e+00]]


In [51]:
sample = [
    [1,2,4],
    [2,3,4],
    [1,4,6]
]

sample = np.array(sample)

sum = np.sum(sample,axis=1)
sum

array([ 7,  9, 11])

# using torch

## Softmax

In [69]:
soft_max = nn.Softmax(dim=1)

In [71]:
multiple_sample = [
    [2,1,3],
    [3,14,5],
    [10,3,1],
]
multiple_sample = torch.tensor(multiple_sample,dtype=torch.float32)

In [72]:
soft_max_out = soft_max(multiple_sample)
print(f" soft max output: {soft_max_out}")

 soft max output: tensor([[2.4473e-01, 9.0031e-02, 6.6524e-01],
        [1.6699e-05, 9.9986e-01, 1.2339e-04],
        [9.9897e-01, 9.1094e-04, 1.2328e-04]])


# Cross Entropy

In [73]:
loss = nn.CrossEntropyLoss()



In [96]:
multiple_sample = [
    [2,1,3],
    [3,14,5],
    [10,3,1],
]

multiple_sample = torch.tensor(multiple_sample,dtype=torch.float32)

y_good = [2,1,1]
y_medium = [2,0,1]

y_bad = [1,0,2]

y_good = torch.tensor(y_good,dtype=torch.long)
y_bad = torch.tensor(y_bad,dtype=torch.long)
y_medium = torch.tensor(y_medium,dtype=torch.long)




In [99]:
# will calcualte the loss of whole dataset

loss_good = loss(multiple_sample,y_good)
loss_bad = loss(multiple_sample,y_bad)
loss_medium = loss(multiple_sample,y_medium)


sample_class_predicition = torch.max(multiple_sample,dim=1)

print(f"loss_good :{loss_good}")
print(f"loss_bad :{loss_bad}")
print(f"loss_medium :{loss_medium}")


# now if the prediction is near the correc the loss will be less
# if the prediction is not corret the loss will be high for whole batch or sample size
print(f"sample_class_prediction:{sample_class_predicition}")



loss_good :2.4695937633514404
loss_bad :7.469593524932861
loss_medium :6.136260509490967
sample_class_prediction:torch.return_types.max(
values=tensor([ 3., 14., 10.]),
indices=tensor([2, 1, 0]))


## eg.
![cross_entropy example](assets\cross_entropy_example.png)


In [100]:
# Multiclass problem
class NeuralNet2(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, num_classes)  
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # no softmax at the end
        return out

model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss()  # (applies Softmax)

# Binary Cross Entropy Loss Function

![binary_classification_problem](assets\binary_classification_problem.png)
![binary_classification_problem](assets\binary_cross_entropy_loss_function.png)

## labeling

good prediction -> 1


bad prediction -> 0

In [101]:
# Binary classification
class NeuralNet1(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet1, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)  
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # sigmoid at the end
        y_pred = torch.sigmoid(out)
        return y_pred

model = NeuralNet1(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()
