# Activation functions

## Why activation functions?
![why_activation_functions](assets/why_activation_functions.png)
![why_activation_functions](assets/why_activation_functions_2.png)


# most popular activation functions are

![most_popular_activation_functions](assets/most_popular_activation_functions.png)

### 1. step function

![step function](assets/step_function.png)

### 2. Sigmoid
![sigmoid](assets/sigmoid_function.png)

### 3. TanH
![TanH](assets/most_popular_activation_functions.png)

### 4. ReLU
![ReLU](assets/relu.png)

### 5. Leaky ReLU
![Leaky ReLU](assets/leaky_relu.png)

### 6. Softmax
![softmax](assets/softmax_activation.png)






# How to use them?

## option 1

In [10]:
import torch.nn as nn
import torch
# option 1

class NeuralNetwork1(nn.Module):

    def __init__(self,num_of_input_features) -> None:
        super(NeuralNetwork1,self).__init__()

        self.input = nn.Linear(in_features=num_of_input_features,out_features=5)

        self.relu = nn.ReLU()

        self.hidden = nn.Linear(in_features=5,out_features=2)

        self.softmax = nn.Softmax(dim=1)

    
    def forward(self,x):

        out = self.input(x)

        out = self.relu(out)

        out = self.hidden(out)

        out = self.softmax(out)

        return out

    


In [11]:
X = [
    [1,2,3],
    [3,4,5],
    [9,8,7]
]
# cause error because of input shape required is (n_sample,10)
model = NeuralNetwork1(num_of_input_features=3)
X = torch.tensor(X,dtype=torch.float32)
y_predict = model(X)
print(y_predict)

tensor([[0.5258, 0.4742],
        [0.5880, 0.4120],
        [0.6219, 0.3781]], grad_fn=<SoftmaxBackward0>)


In [12]:
model = NeuralNetwork1(num_of_input_features=10)
X = torch.rand(size=(100,10),dtype=torch.float32)
y_predict = model(X)
print(y_predict)

tensor([[0.5074, 0.4926],
        [0.5551, 0.4449],
        [0.5562, 0.4438],
        [0.5166, 0.4834],
        [0.5413, 0.4587],
        [0.5529, 0.4471],
        [0.5234, 0.4766],
        [0.5398, 0.4602],
        [0.5731, 0.4269],
        [0.5065, 0.4935],
        [0.5301, 0.4699],
        [0.5499, 0.4501],
        [0.5717, 0.4283],
        [0.5469, 0.4531],
        [0.5253, 0.4747],
        [0.5306, 0.4694],
        [0.4766, 0.5234],
        [0.5141, 0.4859],
        [0.5430, 0.4570],
        [0.5165, 0.4835],
        [0.4727, 0.5273],
        [0.5828, 0.4172],
        [0.5327, 0.4673],
        [0.5771, 0.4229],
        [0.5300, 0.4700],
        [0.6003, 0.3997],
        [0.5251, 0.4749],
        [0.5497, 0.4503],
        [0.5349, 0.4651],
        [0.5798, 0.4202],
        [0.5670, 0.4330],
        [0.5217, 0.4783],
        [0.5779, 0.4221],
        [0.5557, 0.4443],
        [0.5265, 0.4735],
        [0.5420, 0.4580],
        [0.5349, 0.4651],
        [0.5763, 0.4237],
        [0.5

## Option 2

In [17]:
import torch.nn as nn
import torch

# if activation functions not available in torch use this
import torch.nn.functional as F
# option 1

class NeuralNetwork1(nn.Module):

    def __init__(self,num_of_input_features) -> None:
        super(NeuralNetwork1,self).__init__()

        self.input = nn.Linear(in_features=num_of_input_features,out_features=5)

     

        self.hidden = nn.Linear(in_features=5,out_features=2)


    
    def forward(self,x):

        out = self.input(x)

        out = torch.relu(out)

        out = self.hidden(out)

        out = F.softmax(out,dim=1)

        return out


In [18]:
model = NeuralNetwork1(num_of_input_features=10)
X = torch.rand(size=(100,10),dtype=torch.float32)
y_predict = model(X)
print(y_predict)

tensor([[0.5131, 0.4869],
        [0.5078, 0.4922],
        [0.5051, 0.4949],
        [0.5039, 0.4961],
        [0.5088, 0.4912],
        [0.5143, 0.4857],
        [0.5174, 0.4826],
        [0.5146, 0.4854],
        [0.5283, 0.4717],
        [0.4983, 0.5017],
        [0.5144, 0.4856],
        [0.5113, 0.4887],
        [0.5222, 0.4778],
        [0.5162, 0.4838],
        [0.5157, 0.4843],
        [0.5255, 0.4745],
        [0.5054, 0.4946],
        [0.5109, 0.4891],
        [0.5096, 0.4904],
        [0.5076, 0.4924],
        [0.4960, 0.5040],
        [0.4814, 0.5186],
        [0.5160, 0.4840],
        [0.5024, 0.4976],
        [0.5109, 0.4891],
        [0.5094, 0.4906],
        [0.5052, 0.4948],
        [0.5169, 0.4831],
        [0.5161, 0.4839],
        [0.5316, 0.4684],
        [0.5084, 0.4916],
        [0.5090, 0.4910],
        [0.5171, 0.4829],
        [0.5307, 0.4693],
        [0.5117, 0.4883],
        [0.5297, 0.4703],
        [0.5356, 0.4644],
        [0.4974, 0.5026],
        [0.5