In [1]:
import torch

In [11]:
d1 = torch.tensor(
    [
  
    ],

)

d2 = torch.tensor(
    [
        [],
        [],
        [],
        [],
    ]
)
d3 = torch.tensor(
    [
        [
            [],
            [],
            [],
        ],
        [
            [],
            [],
            []
        ],
        [
            [],
            [],
            []
        ],
        [
            [],
            [],
            []
        ],
    ]
)

d1.shape,d2.shape,d3.shape

(torch.Size([0]), torch.Size([4, 0]), torch.Size([4, 3, 0]))

In [12]:
d1 = torch.tensor(
    [
        1,
        2,
        3,
        4
    ],

)

d2 = torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
    ]
)
d3 = torch.tensor(
    [
        [
            [1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
        ],
        [
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
        ],
        [
            [31,32,33,34,35],
            [36,37,38,39,40],
            [41,32,43,44,45]
        ],
        [
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ],
    ]
)

d1.shape,d2.shape,d3.shape

(torch.Size([4]), torch.Size([4, 3]), torch.Size([4, 3, 5]))

# 1-d tensor

In [18]:
# 1-d tensor

d1 = torch.tensor(
    [
        1,
        2,
        3,
        4
    ],

)
index = torch.tensor(
    [
        0,
        3,
        1,
        2
    ]
)
# out = torch.gather(d1,1,index) IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
out = torch.gather(d1,0,index)
out

tensor([1, 4, 2, 3])

# 2d -tensor

In [28]:
# 2-d tensor gathe working
d2 = torch.tensor(
    [  # V V V 
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
    ]
)

index_0d = torch.tensor(
    [      
        # v  v 
        # [0,0], #[1,2]
        # [0,1], #[1,5]
        # [0,2], #[1,8]
        # [0,3],
        # [1,0],
        # [1,1],
        # [1,2],
        [1,3], # [4,11]
        # [2,0],
        # [2,1],
        # [2,2],
        # [2,3],
        # [3,0],
        # [3,1],
        # [3,2],
        # [3,3]
    ]
)
 # RuntimeError: Index tensor must have the same number of dimensions as input tensor
# out = torch.gather(d2,0,index)
# you cannot give 1-d index instead of 2d for 2d tensor how ever you can change the axis to zero or one as like in max  
out = torch.gather(d2,0,index_0d)
index_0d,out

(tensor([[1, 3]]), tensor([[ 4, 11]]))

In [34]:
# 2-d tensor gathe working
d2 = torch.tensor(
    [   # v v v
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
    ]
)

index_0d = torch.tensor(
    [
        [0,0,0], #[1,2] # miss match of tensor cause the index error so cannot be [0,0] instead must be [0,0,0]
        # [0,1], #[1,5]
        # [0,2], #[1,8]
        # [0,3],
        # [1,0],
        # [1,1],
        # [1,2],
        [1,3,1], # [4,11,6]
        # [2,0],
        # [2,1],
        # [2,2],
        # [2,3],
        # [3,0],
        # [3,1],
        # [3,2],
        # [3,3]
    ]
)
 # RuntimeError: Index tensor must have the same number of dimensions as input tensor
# out = torch.gather(d2,0,index)
# you cannot give 1-d index instead of 2d for 2d tensor how ever you can change the axis to zero or one as like in max  
out = torch.gather(d2,0,index_0d)
index_0d,out

(tensor([[0, 0, 0],
         [1, 3, 1]]),
 tensor([[ 1,  2,  3],
         [ 4, 11,  6]]))

In [38]:
# 2-d tensor gathe working
d2 = torch.tensor(
    [
        [1,2,3], # < 
        [4,5,6], # <
        [7,8,9], # <
        [10,11,12], # <
    ]
)

index_1d = torch.tensor(
    [
        [0,1,2], # by default the this indicates to seach in first row of d2 tensor
        [0,1,2], # [4,5,6]
        [0,1,2], # [7,8,9]
        [2,1,0], # [12,11,10]
    ]
)
 # RuntimeError: Index tensor must have the same number of dimensions as input tensor
# out = torch.gather(d2,0,index)
# you cannot give 1-d index instead of 2d for 2d tensor how ever you can change the axis to zero or one as like in max  
out = torch.gather(d2,1,index_1d)
index_0d,out

(tensor([[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [2, 1, 0]]),
 tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [12, 11, 10]]))

# 3d-tensor

In [54]:
# 3d -tensor

d3 = torch.tensor(
    [
        [
            [1,2,3,4,5], 
            [6,7,8,9,10],
            [11,12,13,14,15],
        ],
        [
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
        ],
        [
            [31,32,33,34,35],
            [36,37,38,39,40],
            [41,32,43,44,45]
        ],
        [
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ],
    ]
)

index_0d = torch.tensor(
    [
        [
            [0, # 1st row of first outer2d ,and 1st row inner 3d with index 0
            1, # 2nc row of first outer 2d and  1st row of inner 3d with index 1
            2, # 3rd row of firs outer 2d and 1st row of inner 3d row with index 2
            3],
            [0, #  1st row of outer 2d , and 2nd row of inner  3d  with index 0
            1, # 2nd row of outer 2d and  2nd row of inner 3d with index 1
            2,
            3],
            [0,
            1,
            2,
            3],
            # [0, # 1st row of outer 2d and 4th row of innner 3d with index 0 which is not available
            # 1,
            # 2,
            # 3
            # ]
        ],
        # [ [0,1,2,3] # wrong indexing

        # ],
        # [

        # ],
    ]
)

out = torch.gather(d3,0,index_0d)

out

tensor([[[ 1, 17, 33, 49],
         [ 6, 22, 38, 54],
         [11, 27, 43, 59]]])

In [55]:
# 3d -tensor

d3 = torch.tensor(
    [
        [
            [1,2,3,4,5], 
            [6,7,8,9,10],
            [11,12,13,14,15],
        ],
        [
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
        ],
        [
            [31,32,33,34,35],
            [36,37,38,39,40],
            [41,32,43,44,45]
        ],
        [
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ],
    ]
)

index_0d = torch.tensor(
    [
        [
            [0, # 1st row of first outer2d ,and 1st row inner 3d with index 0 
            1, # 2nc row of first outer 2d and  1st row of inner 3d with index 1
            2, # 3rd row of firs outer 2d and 1st row of inner 3d row with index 2
            ],
            [0, #  1st row of outer 2d , and 2nd row of inner  3d  with index 0
            1, # 2nd row of outer 2d and  2nd row of inner 3d with index 1
            2,
            ],
            [0, # we can decrease indexing to limit the number of column or index we want
            1,
            2,
            ],
            # [0, # 1st row of outer 2d and 4th row of innner 3d with index 0 which is not available
            # 1,
            # 2,
            # 3
            # ]
        ],
        # [ [0,1,2,3] # wrong indexing

        # ],
        # [

        # ],
    ]
)

out = torch.gather(d3,0,index_0d)

out

tensor([[[ 1, 17, 33],
         [ 6, 22, 38],
         [11, 27, 43]]])

In [59]:
# 3d -tensor

d3 = torch.tensor(
    [
        [
            [1,2,3,4,5], 
            [6,7,8,9,10],
            [11,12,13,14,15],
        ],
        [
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
        ],
        [
            [31,32,33,34,35],
            [36,37,38,39,40],
            [41,32,43,44,45]
        ],
        [
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ],
    ]
)

index_1d = torch.tensor(
    [
        [
            [0,1,2,], # always chooose from the 1st row of outer 2d and follow the principle of 1d tensor in the whole inner 3d tensor
            [0,1,2,],
            [0,1,2,],
            [0,1,2]
        ],
        [ 
            [0,1,2],
            [0,1,2],
            [0,1,2],
            [0,1,2]
        ],
        # [

        # ],
        # [
            
        # ]
    ]
)

out = torch.gather(d3,1,index_1d)

out

tensor([[[ 1,  7, 13],
         [ 1,  7, 13],
         [ 1,  7, 13],
         [ 1,  7, 13]],

        [[16, 22, 28],
         [16, 22, 28],
         [16, 22, 28],
         [16, 22, 28]]])

In [63]:
# 3d tensor
d3 = torch.tensor(
    [
        [
            [1,2,3,4,5],  # < select from this with give index 
            [6,7,8,9,10], # < select from this with given index
            [11,12,13,14,15],
        ],
        [
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
        ],
        [
            [31,32,33,34,35],
            [36,37,38,39,40],
            [41,32,43,44,45]
        ],
        [
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ],
    ]
)

index_2d = torch.tensor(
    [
        [
            [0,1,2,3,4], 
            [0,1,2,3,4],
            [0,1,2,3,4],
        ]
    ]
)

out = torch.gather(d3,2,index_2d)

out

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]])

In [103]:
# 3d tensor
d3 = torch.tensor(
    [
        [
            [1,2,3,4,5],  # < select from this with give index 
            [6,7,8,9,10], # < select from this with given index
            [11,12,13,14,15],
        ],
        [
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
        ],
        [
            [31,32,33,34,35],
            [36,37,38,39,40],
            [41,32,43,44,45]
        ],
        [
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ],
    ]
)

index = torch.tensor(
    [
        [0,2],
        [0,1],
        [0,2],
        [1,2],
        
    ]
    )

out = torch.ones((4,2,5))
for i in range(d3.shape[0]):
    # print(d3[i].index_select(0,index[i]))
    out[i] =  d3[i].index_select(0,index[i])

out 

tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [11., 12., 13., 14., 15.]],

        [[16., 17., 18., 19., 20.],
         [21., 22., 23., 24., 25.]],

        [[31., 32., 33., 34., 35.],
         [41., 32., 43., 44., 45.]],

        [[51., 52., 53., 54., 55.],
         [56., 57., 58., 59., 60.]]])

# finnally problem

In [64]:
masked_pos = torch.tensor(
    [
        [ 9,  5,  2,  0,  0],
        [ 9, 13, 12,  0,  0],
        [ 4, 13,  1,  0,  0],
        [11, 15,  4,  0,  0],
        [ 7,  0,  0,  0,  0],
        [ 6,  0,  0,  0,  0]
    ]
)

# solution: 

    # for i in range(output.shape[0]):
    #     h_masked[i] = output[i].index_select(0,masked_pos[i])